<?php

return [
    'title'         => 'Report archives',
    'format'        => 'Format',
    'generated_by'  => 'Generated by',
    'download'      => 'Download',
    'empty'         => [
        'heading'     => 'No archived reports',
        'description' => 'Exported movement reports will appear here for download.',
    ],
];
